# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='value',
            field=models.IntegerField(),
        ),
    ]
