# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataVortex', '0002_auto_20160201_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('buycount', models.PositiveIntegerField()),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='highscore',
            options={'ordering': ['value']},
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='gamename',
        ),
        migrations.AddField(
            model_name='highscore',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='highscore',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highscores', to='DataVortex.Game'),
        ),
    ]
