# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataVortex', '0003_auto_20160202_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='myGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamestate', models.TextField()),
            ],
            options={
                'ordering': ['game'],
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='player',
        ),
        migrations.AlterField(
            model_name='highscore',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataVortex.Game'),
        ),
        migrations.AddField(
            model_name='mygame',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataVortex.Game'),
        ),
        migrations.AddField(
            model_name='mygame',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highscore',
            name='mygame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataVortex.myGame'),
        ),
    ]
