# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0004_auto_20160210_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygame',
            name='gamestate',
            field=models.TextField(blank=True),
        ),
    ]
