# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0005_auto_20160210_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highscore',
            options={'ordering': ['-value']},
        ),
    ]
