# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0006_auto_20160210_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails'),
        ),
    ]
