# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 21:18
from __future__ import unicode_literals

import DataVortex.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0017_auto_20160215_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails', validators=[DataVortex.models.Game.image_check]),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='mygame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataVortex.MyGame'),
        ),
    ]
