# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataVortex', '0023_auto_20160219_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='apikey',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='mygame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataVortex.MyGame'),
        ),
    ]
